In [1]:
# Classification template

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
np.set_printoptions(suppress = True)

In [3]:
##Importing the dataset
dataset = pd.read_csv('train.csv')

dataset['label'] = (dataset['label'] == 'correct').astype('int')

# overwriting data after changing format 
dataset['pickup_time']= pd.to_datetime(dataset["pickup_time"]) 
dataset['drop_time']= pd.to_datetime(dataset["drop_time"])

In [4]:
dataset['pickup_time_year'] = dataset['pickup_time'].dt.year
dataset['pickup_time_month'] =dataset['pickup_time'].dt.month
dataset['pickup_time_week'] =dataset['pickup_time'].dt.week
dataset['pickup_time_day'] = dataset['pickup_time'].dt.day
dataset['pickup_time_hour'] =dataset['pickup_time'].dt.hour
dataset['pickup_time_minute'] =dataset['pickup_time'].dt.minute
dataset['pickup_time_dayofweek'] =dataset['pickup_time'].dt.dayofweek

In [5]:
dataset['drop_time_year'] = dataset['drop_time'].dt.year
dataset['drop_time_month'] =dataset['drop_time'].dt.month
dataset['drop_time_week'] =dataset['drop_time'].dt.week
dataset['drop_time_day'] = dataset['drop_time'].dt.day
dataset['drop_time_hour'] =dataset['drop_time'].dt.hour
dataset['drop_time_minute'] =dataset['drop_time'].dt.minute
dataset['drop_time_dayofweek'] =dataset['drop_time'].dt.dayofweek

In [6]:
dataset.isnull().sum()
#dataset.dropna(how='any')
#print(dataset.shape)

tripid                         0
additional_fare              202
duration                     202
meter_waiting                202
meter_waiting_fare           202
meter_waiting_till_pickup    202
pickup_time                    0
drop_time                      0
pick_lat                       0
pick_lon                       0
drop_lat                       0
drop_lon                       0
fare                         137
label                          0
pickup_time_year               0
pickup_time_month              0
pickup_time_week               0
pickup_time_day                0
pickup_time_hour               0
pickup_time_minute             0
pickup_time_dayofweek          0
drop_time_year                 0
drop_time_month                0
drop_time_week                 0
drop_time_day                  0
drop_time_hour                 0
drop_time_minute               0
drop_time_dayofweek            0
dtype: int64

In [7]:
#Filling missing values with a test statistics like mean, median or mode.
#Showing here with mean only

#mean_value=dataset['additional_fare'].median()
dataset['additional_fare']=dataset['additional_fare'].fillna(0)

mean_value=dataset['duration'].median()
dataset['duration']=dataset['duration'].fillna(mean_value)


mean_value=dataset['meter_waiting'].median()
dataset['meter_waiting']=dataset['meter_waiting'].fillna(0)



mean_value=dataset['meter_waiting_fare'].median()
dataset['meter_waiting_fare']=dataset['meter_waiting_fare'].fillna(0)




mean_value=dataset['meter_waiting_till_pickup'].median()
dataset['meter_waiting_till_pickup']=dataset['meter_waiting_till_pickup'].fillna(0)



mean_value=dataset['fare'].median()
dataset['fare']=dataset['fare'].fillna(0)
print(dataset.head(5))

      tripid  additional_fare  duration  meter_waiting  meter_waiting_fare  \
0  189123628             10.5     834.0           56.0              0.0000
1  189125358             10.5     791.0           47.0              0.0000
2  189125719             10.5    1087.0           80.0              0.0000
3  189127273             10.5     598.0          271.0             15.6638
4  189128020              0.0    1009.5            0.0              0.0000

   meter_waiting_till_pickup         pickup_time           drop_time  \
0                       64.0 2019-11-01 00:20:00 2019-11-01 00:34:00
1                      134.0 2019-11-01 00:56:00 2019-11-01 01:09:00
2                       61.0 2019-11-01 01:08:00 2019-11-01 01:26:00
3                       68.0 2019-11-01 02:27:00 2019-11-01 02:37:00
4                        0.0 2019-11-01 03:34:00 2019-11-01 03:51:00

   pick_lat  pick_lon  ...  pickup_time_hour  pickup_time_minute  \
0   6.86252   79.8993  ...                 0                  20
1   6.88589   79.8984  ...                 0                  56
2   6.90839   79.8651  ...                 1                   8
3   6.92570   79.8895  ...                 2                  27
4   6.87441   79.8615  ...                 3                  34

   pickup_time_dayofweek  drop_time_year  drop_time_month  drop_time_week  \
0                      4            2019               11              44
1                      4            2019               11              44
2                      4            2019               11              44
3                      4            2019               11              44
4                      4            2019               11              44

   drop_time_day  drop_time_hour  drop_time_minute  drop_time_dayofweek
0              1               0                34                    4
1              1               1                 9                    4
2              1               1                26                    4
3              1               2                37                    4
4              1               3                51                    4

[5 rows x 28 columns]

In [8]:

##here find the label values 1 and o 

correct= dataset.loc[dataset['label'] == 1].values
incorrect = dataset.loc[dataset['label'] == 0].values
print(len(correct))

15495

In [9]:
correct_data=dataset.loc[dataset['label'] == 1].head(len(correct))
incorrect_data=dataset.loc[dataset['label'] == 0].head(len(incorrect))

In [10]:
correct_data.head(12)

,tripid,additional_fare,duration,meter_waiting,meter_waiting_fare,meter_waiting_till_pickup,pickup_time,drop_time,pick_lat,pick_lon,...,pickup_time_hour,pickup_time_minute,pickup_time_dayofweek,drop_time_year,drop_time_month,drop_time_week,drop_time_day,drop_time_hour,drop_time_minute,drop_time_dayofweek
0,189123628,10.5,834.0,56.0,0.0000,64.0,2019-11-01 00:20:00,2019-11-01 00:34:00,6.86252,79.8993,...,0,20,4,2019,11,44,1,0,34,4
1,189125358,10.5,791.0,47.0,0.0000,134.0,2019-11-01 00:56:00,2019-11-01 01:09:00,6.88589,79.8984,...,0,56,4,2019,11,44,1,1,9,4
2,189125719,10.5,1087.0,80.0,0.0000,61.0,2019-11-01 01:08:00,2019-11-01 01:26:00,6.90839,79.8651,...,1,8,4,2019,11,44,1,1,26,4
3,189127273,10.5,598.0,271.0,15.6638,68.0,2019-11-01 02:27:00,2019-11-01 02:37:00,6.92570,79.8895,...,2,27,4,2019,11,44,1,2,37,4
4,189128020,0.0,1009.5,0.0,0.0000,0.0,2019-11-01 03:34:00,2019-11-01 03:51:00,6.87441,79.8615,...,3,34,4,2019,11,44,1,3,51,4
5,189129552,10.5,3407.0,182.0,0.0000,112.0,2019-11-01 05:38:00,2019-11-01 06:35:00,7.13402,79.8969,...,5,38,4,2019,11,44,1,6,35,4
6,189132829,10.5,1246.0,487.0,0.0000,133.0,2019-11-01 06:29:00,2019-11-01 06:49:00,6.84371,79.9051,...,6,29,4,2019,11,44,1,6,49,4
7,189135103,10.5,1333.0,295.0,17.1985,212.0,2019-11-01 06:50:00,2019-11-01 07:12:00,6.90760,79.9524,...,6,50,4,2019,11,44,1,7,12,4
8,189139296,10.5,360.0,80.0,4.6640,3.0,2019-11-01 07:00:00,2019-11-01 07:06:00,7.26706,80.6064,...,7,0,4,2019,11,44,1,7,6,4
9,189138671,10.5,1539.0,588.0,33.9864,43.0,2019-11-01 07:02:00,2019-11-01 07:28:00,6.85137,79.9537,...,7,2,4,2019,11,44,1,7,28,4
12,189144528,10.5,2011.0,199.0,0.0000,165.0,2019-11-01 07:44:00,2019-11-01 08:17:00,6.82278,79.9527,...,7,44,4,2019,11,44,1,8,17,4
14,189145904,10.5,335.0,10.0,0.5830,17.0,2019-11-01 07:45:00,2019-11-01 07:51:00,6.85268,79.8631,...,7,45,4,2019,11,44,1,7,51,4

In [11]:
incorrect_data.head()

,tripid,additional_fare,duration,meter_waiting,meter_waiting_fare,meter_waiting_till_pickup,pickup_time,drop_time,pick_lat,pick_lon,...,pickup_time_hour,pickup_time_minute,pickup_time_dayofweek,drop_time_year,drop_time_month,drop_time_week,drop_time_day,drop_time_hour,drop_time_minute,drop_time_dayofweek
10,189135814,10.5,26.0,19.0,0.0000,73.0,2019-11-01 07:27:00,2019-11-01 07:27:00,7.00355,79.8819,...,7,27,4,2019,11,44,1,7,27,4
11,189140969,10.5,31.0,20.0,0.0000,130.0,2019-11-01 07:42:00,2019-11-01 07:42:00,6.90871,79.8978,...,7,42,4,2019,11,44,1,7,42,4
13,189147041,10.5,1260.0,30.0,0.0000,9.0,2019-11-01 07:44:00,2019-11-01 08:05:00,7.12626,79.9817,...,7,44,4,2019,11,44,1,8,5,4
20,189157607,10.5,2956.0,1686.0,97.4508,29.0,2019-11-01 08:40:00,2019-11-01 09:21:00,6.92109,79.8547,...,8,40,4,2019,11,44,1,9,21,4
25,189160756,10.5,358.0,66.0,0.0000,79.0,2019-11-01 08:51:00,2019-11-01 08:57:00,6.05858,80.2003,...,8,51,4,2019,11,44,1,8,57,4

In [12]:
#col2use = ['additional_fare','duration','meter_waiting',
#           'meter_waiting_fare','meter_waiting_till_pickup','pick_lat',
#          'pick_lon','drop_lat','drop_lon','fare',
#         'pickup_time_year','pickup_time_month','pickup_time_week',
#           'pickup_time_day','pickup_time_hour','pickup_time_minute',
#           'pickup_time_dayofweek','drop_time_year','drop_time_month',
#           'drop_time_week',
#          'drop_time_day','drop_time_hour','drop_time_minute',
#           'drop_time_dayofweek']

col2use = ['additional_fare','duration','meter_waiting',
          'meter_waiting_fare','meter_waiting_till_pickup','pick_lat',
          'pick_lon','drop_lat','drop_lon','fare',
           'pickup_time_day','pickup_time_hour','pickup_time_minute',
           'drop_time_day','drop_time_hour','drop_time_minute']

#features selected accordong to feature selection algorithm

#features = ['additional_fare','duration','meter_waiting',
 #          'meter_waiting_fare','meter_waiting_till_pickup','pick_lat',
  #        'pick_lon','drop_lat','drop_lon','fare','pickup_time_day','drop_time_day']

#features=['duration','fare','pickup_time_day','drop_time_day']
#features selected by feature importance

#features=['duration', 'fare', 'pickup_time_month',
#       'pickup_time_week', 'pickup_time_day', 'drop_time_month',
#       'drop_time_week', 'drop_time_day']

features = ['additional_fare','duration','meter_waiting',
          'meter_waiting_fare','meter_waiting_till_pickup','fare']

correct1=correct_data[features].values
correct1_label=correct_data['label'].values
incorrect1=incorrect_data[features].values
incorrect1_label=incorrect_data['label'].values
#print(correct1[4])

In [13]:
print(correct1.shape)
print(incorrect1.shape)
# Highly imbalanced dataset (bias towards the positive class)

(15495, 6)
(1681, 6)

In [14]:
# Balancing classes by undersampling the positive class
correct1 = correct1[0:incorrect1.shape[0]]
correct1_label = correct1_label[0:incorrect1.shape[0]]
correct1.shape

(1681, 6)

In [15]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train1, y_test1 = train_test_split(correct1, correct1_label, test_size = 0.3, random_state = 0)
X_train2, X_test2, y_train2, y_test2 = train_test_split(incorrect1, incorrect1_label, test_size = 0.3, random_state = 0)

print(len(X_train1))

1176

In [16]:

x_train=[]
x_test=[]
y_train=[]
y_test=[]
for k in range(0,len(X_train1)):
        x_train.append(X_train1[k])
        

    
for k in range(0,len(X_train2)):   
        x_train.append(X_train2[k])
        
  

for k in range(0,len(X_test1)):   
        x_test.append(X_test1[k])
        
for k in range(0,len(X_test2)):   
        x_test.append(X_test2[k]) 
        
for k in range(0,len(y_train1)):   
        y_train.append(y_train1[k])
        
for k in range(0,len(y_train2)):   
         y_train.append(y_train2[k])        
        
 

for k in range(0,len(y_test1)):   
        y_test.append(y_test1[k])
        
for k in range(0,len(y_test2)):   
        y_test.append(y_test2[k])        
        


x_train=np.array(x_train)
x_test=np.array(x_test)
y_train=np.array(y_train)
y_test=np.array(y_test)
# print(x_test.shape)

In [17]:
#Implementation ANN classsifier

In [18]:
# Importing the Keras libraries and packages
#import tensorflow
#from tensorflow.keras.models import Sequential
#from tensorflow.keras.layers import Dense

In [19]:
# Normalizing data
mean = x_train.mean(axis = 0)
std = x_train.std(axis = 0)
x_train = (x_train - mean)/std
x_test = (x_test - mean)/std

# Shuffling the data
np.random.seed(0)
order = np.argsort(np.random.random(y_train.shape))
x_train_shuff = x_train[order]
y_train_shuff = y_train[order]

In [20]:
# Initialising the ANN
#classifier = Sequential()

In [21]:
# Adding the input layer and the first hidden layer
#classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 24))

In [22]:
# Adding the second hidden layer
#classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [23]:
# Adding the output layer
#classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [24]:
# Compiling the ANN
#classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [25]:
# Fitting the ANN to the Training set
#classifier.fit(x_train, y_train, batch_size = 10, epochs = 100)

In [26]:
#test_loss, test_acc = classifier.evaluate(x_test,  y_test, verbose=2)

#print('\nTest accuracy:', test_acc)

In [27]:
print(x_train[y_train == 0].shape)
print(x_train[y_train == 1].shape)

(1176, 6)
(1176, 6)

In [28]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

from sklearn.feature_selection import RFE
#sel = RFE(RandomForestClassifier(n_estimators=100, random_state=0, n_jobs=-1), n_features_to_select = 15)
#sel.fit(X_train, y_train)

#Create a Gaussian Classifier
#clf=RandomForestClassifier(n_estimators=100)
clf=RandomForestClassifier(n_estimators=100, random_state=0, n_jobs=-1)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(x_train_shuff, y_train_shuff)

#y_pred=clf.predict(X_test)
#lf.get_support()

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [29]:
#col2use

#features=['duration','fare','pickup_time_day','drop_time_day']

#np.mean(clf.estimator_.feature_importances_)

In [30]:
#clf.estimator_.feature_importances_

#x_train.fillna(x_train.mean(), inplace=True)

#from sklearn.svm import SVC
#clf = SVC(kernel='rbf')
#clf.fit(x_train_shuff, y_train_shuff)

In [31]:
# Implementing a KNN

#from sklearn.neighbors import KNeighborsClassifier
#clf = KNeighborsClassifier(n_neighbors=3)
#clf.fit(x_train_shuff, y_train_shuff)

In [32]:
#x_train_rfc=transform

In [33]:
# y_pred = svclassifier.predict(x_test)
from sklearn.metrics import classification_report, confusion_matrix
# print(confusion_matrix(y_test, y_pred))
# print(classification_report(y_test, y_pred))
# print(y_pred)

y_pred = clf.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[410  95]
 [ 64 441]]

In [34]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.81      0.84       505
           1       0.82      0.87      0.85       505

    accuracy                           0.84      1010
   macro avg       0.84      0.84      0.84      1010
weighted avg       0.84      0.84      0.84      1010

In [35]:
tn = cm[0, 0]
fp = cm[0, 1]
fn = cm[1, 0]
tp = cm[1, 1]

precision = tp/(tp + fp)
recall = tp/(tp + fn)
accuracy = (tp + tn)/(tp + fp + tn + fn)
f1 = (2*(precision*recall))/(precision + recall)

print('Precision: ', precision*100, '%', sep = '')
print('Recall: ', recall*100, '%', sep = '')
print('Accuracy: ', accuracy*100, '%', sep = '')
print('F1 score: ', f1*100, '%', sep = '')

Precision: 82.27611940298507%
Recall: 87.32673267326733%
Accuracy: 84.25742574257426%
F1 score: 84.72622478386167%

In [36]:
# cf = confusion_matrix(y_test, y_pred).ravel()
# tp, fp, fn, tn = cf
# precision = tp/(tp + fp)
# recall = tp/(tp + fn)
# f1 = 2*((precision*recall)/(precision + recall))

# print('Precision:\t', round(precision*100), '%')
# print('Recall:\t\t', round(recall*100), '%')
# print('F1 score:\t', round(f1*100), '%')

In [37]:
#prediction = pd.DataFrame(y_pred, columns=['Class']).to_csv('submission.csv')

In [38]:
#Importing the dataset
dataset2 = pd.read_csv('test.csv')
# overwriting data after changing format 
dataset2['pickup_time']= pd.to_datetime(dataset2["pickup_time"]) 
dataset2['drop_time']= pd.to_datetime(dataset2["drop_time"])


dataset2['pickup_time_year'] = dataset2['pickup_time'].dt.year
dataset2['pickup_time_month'] =dataset2['pickup_time'].dt.month
dataset2['pickup_time_week'] =dataset2['pickup_time'].dt.week
dataset2['pickup_time_day'] = dataset2['pickup_time'].dt.day
dataset2['pickup_time_hour'] =dataset2['pickup_time'].dt.hour
dataset2['pickup_time_minute'] =dataset2['pickup_time'].dt.minute
dataset2['pickup_time_dayofweek'] =dataset2['pickup_time'].dt.dayofweek


dataset2['drop_time_year'] = dataset2['drop_time'].dt.year
dataset2['drop_time_month'] =dataset2['drop_time'].dt.month
dataset2['drop_time_week'] =dataset2['drop_time'].dt.week
dataset2['drop_time_day'] = dataset2['drop_time'].dt.day
dataset2['drop_time_hour'] =dataset2['drop_time'].dt.hour
dataset2['drop_time_minute'] =dataset2['drop_time'].dt.minute
dataset2['drop_time_dayofweek'] =dataset2['drop_time'].dt.dayofweek


#col2use = ['additional_fare','duration','meter_waiting',
#           'meter_waiting_fare','meter_waiting_till_pickup','pick_lat',
#           'pick_lon','drop_lat','drop_lon','fare',
#         'pickup_time_year','pickup_time_month','pickup_time_week',
#           'pickup_time_day','pickup_time_hour','pickup_time_minute',
#           'pickup_time_dayofweek','drop_time_year','drop_time_month',
#           'drop_time_week',
#          'drop_time_day','drop_time_hour','drop_time_minute',
#           'drop_time_dayofweek']



new_test=dataset2[features].values
new_test=np.array(new_test)
print(new_test.shape)


##normalize
new_test = (new_test - mean)/std


y_pred2 = clf.predict(new_test)
prediction2 = pd.DataFrame(y_pred2, columns=['Class']).to_csv('submission_kaggle_finaltest5.csv')

(8576, 6)