In [4]:
# Classification template

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
np.set_printoptions(suppress = True)

In [6]:
##Importing the dataset
dataset = pd.read_csv('train.csv')

dataset['label'] = (dataset['label'] == 'correct').astype('int')

# overwriting data after changing format 
dataset['pickup_time']= pd.to_datetime(dataset["pickup_time"]) 
dataset['drop_time']= pd.to_datetime(dataset["drop_time"])

In [7]:
dataset['pickup_time_year'] = dataset['pickup_time'].dt.year
dataset['pickup_time_month'] =dataset['pickup_time'].dt.month
dataset['pickup_time_week'] =dataset['pickup_time'].dt.week
dataset['pickup_time_day'] = dataset['pickup_time'].dt.day
dataset['pickup_time_hour'] =dataset['pickup_time'].dt.hour
dataset['pickup_time_minute'] =dataset['pickup_time'].dt.minute
dataset['pickup_time_dayofweek'] =dataset['pickup_time'].dt.dayofweek

In [8]:
dataset['drop_time_year'] = dataset['drop_time'].dt.year
dataset['drop_time_month'] =dataset['drop_time'].dt.month
dataset['drop_time_week'] =dataset['drop_time'].dt.week
dataset['drop_time_day'] = dataset['drop_time'].dt.day
dataset['drop_time_hour'] =dataset['drop_time'].dt.hour
dataset['drop_time_minute'] =dataset['drop_time'].dt.minute
dataset['drop_time_dayofweek'] =dataset['drop_time'].dt.dayofweek

In [9]:
dataset.isnull().sum()
#dataset.dropna(how='any')
#print(dataset.shape)

tripid                         0
additional_fare              202
duration                     202
meter_waiting                202
meter_waiting_fare           202
meter_waiting_till_pickup    202
pickup_time                    0
drop_time                      0
pick_lat                       0
pick_lon                       0
drop_lat                       0
drop_lon                       0
fare                         137
label                          0
pickup_time_year               0
pickup_time_month              0
pickup_time_week               0
pickup_time_day                0
pickup_time_hour               0
pickup_time_minute             0
pickup_time_dayofweek          0
drop_time_year                 0
drop_time_month                0
drop_time_week                 0
drop_time_day                  0
drop_time_hour                 0
drop_time_minute               0
drop_time_dayofweek            0
dtype: int64

In [10]:
#Filling missing values with a test statistics like mean, median or mode.
#Showing here with mean only

mean_value=dataset['additional_fare'].median()
dataset['additional_fare']=dataset['additional_fare'].fillna(mean_value)

mean_value=dataset['duration'].median()
dataset['duration']=dataset['duration'].fillna(mean_value)


mean_value=dataset['meter_waiting'].median()
dataset['meter_waiting']=dataset['meter_waiting'].fillna(mean_value)



mean_value=dataset['meter_waiting_fare'].median()
dataset['meter_waiting_fare']=dataset['meter_waiting_fare'].fillna(mean_value)




mean_value=dataset['meter_waiting_till_pickup'].median()
dataset['meter_waiting_till_pickup']=dataset['meter_waiting_till_pickup'].fillna(mean_value)



mean_value=dataset['fare'].median()
dataset['fare']=dataset['fare'].fillna(mean_value)
print(dataset.head(5))

      tripid  additional_fare  duration  meter_waiting  meter_waiting_fare  \
0  189123628             10.5     834.0           56.0              0.0000
1  189125358             10.5     791.0           47.0              0.0000
2  189125719             10.5    1087.0           80.0              0.0000
3  189127273             10.5     598.0          271.0             15.6638
4  189128020             10.5    1009.5          123.0              0.1166

   meter_waiting_till_pickup         pickup_time           drop_time  \
0                       64.0 2019-11-01 00:20:00 2019-11-01 00:34:00
1                      134.0 2019-11-01 00:56:00 2019-11-01 01:09:00
2                       61.0 2019-11-01 01:08:00 2019-11-01 01:26:00
3                       68.0 2019-11-01 02:27:00 2019-11-01 02:37:00
4                       73.0 2019-11-01 03:34:00 2019-11-01 03:51:00

   pick_lat  pick_lon  ...  pickup_time_hour  pickup_time_minute  \
0   6.86252   79.8993  ...                 0                  20
1   6.88589   79.8984  ...                 0                  56
2   6.90839   79.8651  ...                 1                   8
3   6.92570   79.8895  ...                 2                  27
4   6.87441   79.8615  ...                 3                  34

   pickup_time_dayofweek  drop_time_year  drop_time_month  drop_time_week  \
0                      4            2019               11              44
1                      4            2019               11              44
2                      4            2019               11              44
3                      4            2019               11              44
4                      4            2019               11              44

   drop_time_day  drop_time_hour  drop_time_minute  drop_time_dayofweek
0              1               0                34                    4
1              1               1                 9                    4
2              1               1                26                    4
3              1               2                37                    4
4              1               3                51                    4

[5 rows x 28 columns]

In [11]:

##here find the label values 1 and o 

correct= dataset.loc[dataset['label'] == 1].values
incorrect = dataset.loc[dataset['label'] == 0].values
print(len(correct))

15495

In [12]:
correct_data=dataset.loc[dataset['label'] == 1].head(len(correct))
incorrect_data=dataset.loc[dataset['label'] == 0].head(len(incorrect))

In [13]:
correct_data.head(12)

,tripid,additional_fare,duration,meter_waiting,meter_waiting_fare,meter_waiting_till_pickup,pickup_time,drop_time,pick_lat,pick_lon,...,pickup_time_hour,pickup_time_minute,pickup_time_dayofweek,drop_time_year,drop_time_month,drop_time_week,drop_time_day,drop_time_hour,drop_time_minute,drop_time_dayofweek
0,189123628,10.5,834.0,56.0,0.0000,64.0,2019-11-01 00:20:00,2019-11-01 00:34:00,6.86252,79.8993,...,0,20,4,2019,11,44,1,0,34,4
1,189125358,10.5,791.0,47.0,0.0000,134.0,2019-11-01 00:56:00,2019-11-01 01:09:00,6.88589,79.8984,...,0,56,4,2019,11,44,1,1,9,4
2,189125719,10.5,1087.0,80.0,0.0000,61.0,2019-11-01 01:08:00,2019-11-01 01:26:00,6.90839,79.8651,...,1,8,4,2019,11,44,1,1,26,4
3,189127273,10.5,598.0,271.0,15.6638,68.0,2019-11-01 02:27:00,2019-11-01 02:37:00,6.92570,79.8895,...,2,27,4,2019,11,44,1,2,37,4
4,189128020,10.5,1009.5,123.0,0.1166,73.0,2019-11-01 03:34:00,2019-11-01 03:51:00,6.87441,79.8615,...,3,34,4,2019,11,44,1,3,51,4
5,189129552,10.5,3407.0,182.0,0.0000,112.0,2019-11-01 05:38:00,2019-11-01 06:35:00,7.13402,79.8969,...,5,38,4,2019,11,44,1,6,35,4
6,189132829,10.5,1246.0,487.0,0.0000,133.0,2019-11-01 06:29:00,2019-11-01 06:49:00,6.84371,79.9051,...,6,29,4,2019,11,44,1,6,49,4
7,189135103,10.5,1333.0,295.0,17.1985,212.0,2019-11-01 06:50:00,2019-11-01 07:12:00,6.90760,79.9524,...,6,50,4,2019,11,44,1,7,12,4
8,189139296,10.5,360.0,80.0,4.6640,3.0,2019-11-01 07:00:00,2019-11-01 07:06:00,7.26706,80.6064,...,7,0,4,2019,11,44,1,7,6,4
9,189138671,10.5,1539.0,588.0,33.9864,43.0,2019-11-01 07:02:00,2019-11-01 07:28:00,6.85137,79.9537,...,7,2,4,2019,11,44,1,7,28,4
12,189144528,10.5,2011.0,199.0,0.0000,165.0,2019-11-01 07:44:00,2019-11-01 08:17:00,6.82278,79.9527,...,7,44,4,2019,11,44,1,8,17,4
14,189145904,10.5,335.0,10.0,0.5830,17.0,2019-11-01 07:45:00,2019-11-01 07:51:00,6.85268,79.8631,...,7,45,4,2019,11,44,1,7,51,4

In [14]:
incorrect_data.head()

,tripid,additional_fare,duration,meter_waiting,meter_waiting_fare,meter_waiting_till_pickup,pickup_time,drop_time,pick_lat,pick_lon,...,pickup_time_hour,pickup_time_minute,pickup_time_dayofweek,drop_time_year,drop_time_month,drop_time_week,drop_time_day,drop_time_hour,drop_time_minute,drop_time_dayofweek
10,189135814,10.5,26.0,19.0,0.0000,73.0,2019-11-01 07:27:00,2019-11-01 07:27:00,7.00355,79.8819,...,7,27,4,2019,11,44,1,7,27,4
11,189140969,10.5,31.0,20.0,0.0000,130.0,2019-11-01 07:42:00,2019-11-01 07:42:00,6.90871,79.8978,...,7,42,4,2019,11,44,1,7,42,4
13,189147041,10.5,1260.0,30.0,0.0000,9.0,2019-11-01 07:44:00,2019-11-01 08:05:00,7.12626,79.9817,...,7,44,4,2019,11,44,1,8,5,4
20,189157607,10.5,2956.0,1686.0,97.4508,29.0,2019-11-01 08:40:00,2019-11-01 09:21:00,6.92109,79.8547,...,8,40,4,2019,11,44,1,9,21,4
25,189160756,10.5,358.0,66.0,0.0000,79.0,2019-11-01 08:51:00,2019-11-01 08:57:00,6.05858,80.2003,...,8,51,4,2019,11,44,1,8,57,4

In [15]:
col2use = ['additional_fare','duration','meter_waiting',
           'meter_waiting_fare','meter_waiting_till_pickup','pick_lat',
          'pick_lon','drop_lat','drop_lon','fare',
         'pickup_time_year','pickup_time_month','pickup_time_week',
           'pickup_time_day','pickup_time_hour','pickup_time_minute',
           'pickup_time_dayofweek','drop_time_year','drop_time_month',
           'drop_time_week',
          'drop_time_day','drop_time_hour','drop_time_minute',
           'drop_time_dayofweek']

#col2use = ['additional_fare','duration','meter_waiting',
 #         'meter_waiting_fare','meter_waiting_till_pickup','pick_lat',
  #        'pick_lon','drop_lat','drop_lon','fare',
   #        'pickup_time_day','pickup_time_hour','pickup_time_minute',
     #      'drop_time_day','drop_time_hour','drop_time_minute']


#features selected accordong to feature selection algorithm

#features = ['additional_fare','duration','meter_waiting',
 #          'meter_waiting_fare','meter_waiting_till_pickup','pick_lat',
  #        'pick_lon','drop_lat','drop_lon','fare','pickup_time_day','drop_time_day']

#features=['duration','fare','pickup_time_day','drop_time_day']


correct1=correct_data[col2use].values
correct1_label=correct_data['label'].values
incorrect1=incorrect_data[col2use].values
incorrect1_label=incorrect_data['label'].values
#print(correct1[4])

In [16]:
print(correct1.shape)
print(incorrect1.shape)
# Highly imbalanced dataset (bias towards the positive class)

(15495, 24)
(1681, 24)

In [17]:
# Balancing classes by undersampling the positive class
correct1 = correct1[0:incorrect1.shape[0]]
correct1_label = correct1_label[0:incorrect1.shape[0]]
correct1_label.shape
incorrect1_label.shape

(1681,)

In [18]:
data=np.vstack((correct1,incorrect1))
#print(data.shape)


x= pd.DataFrame(data = data, columns=col2use)
x.head()

#y=np.vstack((correct1_label,incorrect1_label))
y=np.concatenate((correct1_label,incorrect1_label), axis=None)




from sklearn.utils import shuffle

x, y = shuffle(x, y)

In [19]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)
X_train.shape, X_test.shape

((2689, 24), (673, 24))

In [20]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
def run_randomForest(X_train, X_test, y_train, y_test):
    clf = RandomForestClassifier(n_estimators=100, random_state=0, n_jobs=-1)
    clf.fit(X_train, y_train)
   
    y_pred = clf.predict(X_test)
    cm = confusion_matrix(y_test,y_pred)
    print('Accuracy: ', accuracy_score(y_test, y_pred))
    print(cm)
    print(classification_report(y_test, y_pred))
    
    
    tn = cm[0, 0]
    fp = cm[0, 1]
    fn = cm[1, 0]
    tp = cm[1, 1]

    precision = tp/(tp + fp)
    recall = tp/(tp + fn)
    accuracy = (tp + tn)/(tp + fp + tn + fn)
    f1 = (2*(precision*recall))/(precision + recall)

    print('Precision: ', precision*100, '%', sep = '')
    print('Recall: ', recall*100, '%', sep = '')
    print('Accuracy: ', accuracy*100, '%', sep = '')
    print('F1 score: ', f1*100, '%', sep = '')

In [21]:
#Implementation ANN classsifier

In [22]:
# Importing the Keras libraries and packages
#import tensorflow
#from tensorflow.keras.models import Sequential
#from tensorflow.keras.layers import Dense

In [23]:
#Feature selection by feature importance of random forest classifier

from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel


sel = SelectFromModel(RandomForestClassifier(n_estimators=100, random_state=0, n_jobs=-1))
sel.fit(X_train, y_train)
sel.get_support()
features = X_train.columns[sel.get_support()]
features

Index(['duration', 'fare', 'pickup_time_year', 'pickup_time_month',
       'pickup_time_week', 'pickup_time_day', 'drop_time_month',
       'drop_time_week', 'drop_time_day'],
      dtype='object')

In [24]:
#get the mean of the selected features with the funcion mean()
#From this we can observe that the features which have more than mean have more importance and whic has less than mean are less importance.
np.mean(sel.estimator_.feature_importances_)
sel.estimator_.feature_importances_

array([0.00428505, 0.04629207, 0.02050117, 0.01234232, 0.01998595,
       0.01344658, 0.01462631, 0.01479973, 0.01484183, 0.04498027,
       0.04727925, 0.04979392, 0.09132803, 0.1373761 , 0.01184105,
       0.01105617, 0.00647623, 0.03559515, 0.05546792, 0.15593412,
       0.16494099, 0.01051902, 0.01109448, 0.00519631])

In [25]:
X_train_rfc = sel.transform(X_train)
X_test_rfc = sel.transform(X_test)


run_randomForest(X_train_rfc, X_test_rfc, y_train, y_test)

Accuracy:  0.9613670133729569
[[318  20]
 [  6 329]]
              precision    recall  f1-score   support

           0       0.98      0.94      0.96       338
           1       0.94      0.98      0.96       335

    accuracy                           0.96       673
   macro avg       0.96      0.96      0.96       673
weighted avg       0.96      0.96      0.96       673

Precision: 94.26934097421203%
Recall: 98.2089552238806%
Accuracy: 96.13670133729569%
F1 score: 96.19883040935673%

In [26]:
#Importing the dataset
dataset2 = pd.read_csv('test.csv')
# overwriting data after changing format 
dataset2['pickup_time']= pd.to_datetime(dataset2["pickup_time"]) 
dataset2['drop_time']= pd.to_datetime(dataset2["drop_time"])


dataset2['pickup_time_year'] = dataset2['pickup_time'].dt.year
dataset2['pickup_time_month'] =dataset2['pickup_time'].dt.month
dataset2['pickup_time_week'] =dataset2['pickup_time'].dt.week
dataset2['pickup_time_day'] = dataset2['pickup_time'].dt.day
dataset2['pickup_time_hour'] =dataset2['pickup_time'].dt.hour
dataset2['pickup_time_minute'] =dataset2['pickup_time'].dt.minute
dataset2['pickup_time_dayofweek'] =dataset2['pickup_time'].dt.dayofweek


dataset2['drop_time_year'] = dataset2['drop_time'].dt.year
dataset2['drop_time_month'] =dataset2['drop_time'].dt.month
dataset2['drop_time_week'] =dataset2['drop_time'].dt.week
dataset2['drop_time_day'] = dataset2['drop_time'].dt.day
dataset2['drop_time_hour'] =dataset2['drop_time'].dt.hour
dataset2['drop_time_minute'] =dataset2['drop_time'].dt.minute
dataset2['drop_time_dayofweek'] =dataset2['drop_time'].dt.dayofweek



new_test=dataset2[features].values
new_test=np.array(new_test)
print(new_test.shape)





y_pred2 = clf.predict(new_test)
prediction2 = pd.DataFrame(y_pred2, columns=['Class']).to_csv('submission_kaggle_final6.csv')

FileNotFoundError: [Errno 2] File test.csv does not exist: 'test.csv'

In [ ]:
prediction = pd.DataFrame(y_pred, columns=['Class']).to_csv('submission.csv')

In [ ]:
#Importing the dataset
dataset2 = pd.read_csv('test.csv')
# overwriting data after changing format 
dataset2['pickup_time']= pd.to_datetime(dataset2["pickup_time"]) 
dataset2['drop_time']= pd.to_datetime(dataset2["drop_time"])


dataset2['pickup_time_year'] = dataset2['pickup_time'].dt.year
dataset2['pickup_time_month'] =dataset2['pickup_time'].dt.month
dataset2['pickup_time_week'] =dataset2['pickup_time'].dt.week
dataset2['pickup_time_day'] = dataset2['pickup_time'].dt.day
dataset2['pickup_time_hour'] =dataset2['pickup_time'].dt.hour
dataset2['pickup_time_minute'] =dataset2['pickup_time'].dt.minute
dataset2['pickup_time_dayofweek'] =dataset2['pickup_time'].dt.dayofweek


dataset2['drop_time_year'] = dataset2['drop_time'].dt.year
dataset2['drop_time_month'] =dataset2['drop_time'].dt.month
dataset2['drop_time_week'] =dataset2['drop_time'].dt.week
dataset2['drop_time_day'] = dataset2['drop_time'].dt.day
dataset2['drop_time_hour'] =dataset2['drop_time'].dt.hour
dataset2['drop_time_minute'] =dataset2['drop_time'].dt.minute
dataset2['drop_time_dayofweek'] =dataset2['drop_time'].dt.dayofweek


#col2use = ['additional_fare','duration','meter_waiting',
#           'meter_waiting_fare','meter_waiting_till_pickup','pick_lat',
#           'pick_lon','drop_lat','drop_lon','fare',
#         'pickup_time_year','pickup_time_month','pickup_time_week',
#           'pickup_time_day','pickup_time_hour','pickup_time_minute',
#           'pickup_time_dayofweek','drop_time_year','drop_time_month',
#           'drop_time_week',
#          'drop_time_day','drop_time_hour','drop_time_minute',
#           'drop_time_dayofweek']



new_test=dataset2[features].values
new_test=np.array(new_test)
print(new_test.shape)


##normalize
new_test = (new_test - mean)/std


y_pred2 = clf.predict(new_test)
prediction2 = pd.DataFrame(y_pred2, columns=['Class']).to_csv('submission_kaggle_final5.csv')